AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-product-api

  Sample SAM Template for lambda-product-api

Globals:
  Function:
    Timeout: 3

Resources:
  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/update-product.lambdaHandler
      Runtime: nodejs20.x
      Tracing: Active
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        UpdateProduct:
          Type: Api
          Properties:
            Path: /product/{id}
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/handlers/update-product.ts

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Products
      AttributeDefinitions:
        - AttributeName: _id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: _id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL


Outputs:
  UpdateProductApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Product function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product/"
  UpdateProductFunction:
    Description: "Update product Lambda Function ARN"
    Value: !GetAtt UpdateProductFunction.Arn
  UpdateProductFunctionIamRole:
    Description: "Implicit IAM Role created for Update Product function"
    Value: !GetAtt UpdateProductFunctionRole.Arn
